### ISSUE TITLE
 TypeError: bananojs.getAccountFromSeed is not a function when running npm start

### ISSUE THREAD

**Issue by JetpackFandango** [BananoCoin/bananojs#13]
After cloning the repo, editing the config.js file, running npm install and then running npm start I get this error:
```
> banano-p2w-runner@1.0.0 start C:\Users\mhudg\Apps\banano\banano-p2w-runner
> node -max-old-space-size=1700 scripts/index.js

(node:39952) UnhandledPromiseRejectionWarning: TypeError: bananojs.getAccountFromSeed is not a function
    at Object.init (C:\Users\mhudg\Apps\banano\banano-p2w-runner\scripts\game.js:37:29)
    at init (C:\Users\mhudg\Apps\banano\banano-p2w-runner\scripts\index.js:45:8)
    at Object.<anonymous> (C:\Users\mhudg\Apps\banano\banano-p2w-runner\scripts\index.js:127:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by JetpackFandango** [comment]
Accidentally opened this on the wrong repo
